name: 'Assignments Completion Check'
description: 'Blocks push if employee has not completed required assignments'
inputs:
  target_repo:
    description: 'Repository to check (format: owner/repo)'
    required: true
    default: ${{ github.repository }}
  gh_token:
    description: 'GITHUB_TOKEN/PAT with proper permissions'
    required: true
  api_endpoint:
    description: 'SecureFlag API endpoint'
    required: false
  api_token:
    description: 'SecureFlag API token'
    required: true
  assignment_check_type:
    description: 'Type of assignment check: completed_initial, completed_pending, or not_expired'
    required: true
    default: 'completed_pending'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 1) Extract committer email
    - name: Extract committer email
      id: extract
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        TARGET_REPO: ${{ inputs.target_repo }}
      run: |
        # Extract committer email
        RESPONSE=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${TARGET_REPO}/commits/${{ github.sha }})
        COMMITTER_EMAIL=$(echo "$RESPONSE" | jq -r '.commit.author.email')

        MAX_RETRIES=10
        RETRY_DELAY=5
        PR_JSON=""
        for ((i=1; i<=$MAX_RETRIES; i++)); do
          PR_JSON=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${TARGET_REPO}/commits/${{ github.sha }}/pulls)

          TRIMMED_JSON=$(echo "$PR_JSON" | tr -d '[:space:]')
          if [ -n "$PR_JSON" ] && [ "$TRIMMED_JSON" != "[]" ]; then
            break
          fi

          if [ $i -lt $MAX_RETRIES ]; then
            echo "PR not found, retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          fi
        done

        PR_No=$(echo "$PR_JSON" | jq -r '.[0].number')

        if [[ "$COMMITTER_EMAIL" == *users.noreply.github.com ]]; then
          echo "⚠️ The email address is private, skipping"
          COMMITTER_EMAIL=""
        fi

        echo "pr_no=$PR_No" >> $GITHUB_OUTPUT
        echo "committer_email=$COMMITTER_EMAIL" >> $GITHUB_OUTPUT
        echo "Extracted committer email: $COMMITTER_EMAIL"

    # 2) Verify assignment completion
    - name: Verify assignments
      id: verify_assignments
      if: steps.extract.outputs.committer_email != ''
      shell: bash
      env:
        COMMITTER_EMAIL: ${{ steps.extract.outputs.committer_email }}
        ASSIGNMENT_CHECK_TYPE: ${{ inputs.assignment_check_type }}
        PROVIDED_API_ENDPOINT: ${{ inputs.api_endpoint }}
      run: |
        # Call SecureFlag API to verify assignment status
        API_ENDPOINT=${PROVIDED_API_ENDPOINT:-"https://api.secureflag.com/rest/management/v2/users/hasCompletedTraining"}

        # Build API request payload based on assignment check type
        PAYLOAD=""
        REQUIREMENT_NAME=""
        REQUIREMENT_ΝΟΤΜΕΤ_NAME=""
        case "$ASSIGNMENT_CHECK_TYPE" in
          completed_initial)
            PAYLOAD="{\"user\":\"$COMMITTER_EMAIL\",\"hasCompletedInitialAssignments\":true}"
            REQUIREMENT_NAME="completed initial assignments"
            REQUIREMENT_ΝΟΤΜΕΤ_NAME="initial assignments"
            ;;
          completed_pending)
            PAYLOAD="{\"user\":\"$COMMITTER_EMAIL\",\"hasCompletedPendingAssignments\":true}"
            REQUIREMENT_NAME="completed pending assignments"
            REQUIREMENT_ΝΟΤΜΕΤ_NAME="pending assignments"
            ;;
          not_expired)
            PAYLOAD="{\"user\":\"$COMMITTER_EMAIL\",\"hasNotExpiredAssignments\":true}"
            REQUIREMENT_NAME="no expired assignments"
            REQUIREMENT_ΝΟΤΜΕΤ_NAME="expired assignments"
            ;;
          *)
            echo "❌ Invalid assignment check type: $ASSIGNMENT_CHECK_TYPE"
            echo "Valid types: completed_initial, completed_pending, not_expired"
            exit 1
            ;;
        esac

        echo "Verifying $REQUIREMENT_NAME for \"$COMMITTER_EMAIL\""

        response=$(curl -s \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "$API_ENDPOINT")

        result=$(echo "$response" | jq -r '.result')
        error=$(echo "$response" | jq -r '.error')
        errorMsg=$(echo "$response" | jq -r '.errorMsg')

        if [[ "$error" == "true" ]]; then
          if [[ "$errorMsg" == "EmptyUser" ]]; then
            message="⚠️ Skipping assignment verification, \"$COMMITTER_EMAIL\" is not a valid user in SecureFlag. Please ensure your email is registered."
            echo "$message"
            echo "requirement_name=$REQUIREMENT_NAME" >> $GITHUB_OUTPUT
            echo "skip_reason=EmptyUser" >> $GITHUB_OUTPUT
            exit 0
          else
            # If it's a generic API error, just log it and allow the push
            message="⚠️ Skipping assignment verification, API returned $errorMsg"
            echo "$message"
            echo "requirement_name=$REQUIREMENT_NAME" >> $GITHUB_OUTPUT
            echo "skip_reason=APIError" >> $GITHUB_OUTPUT
            exit 0
          fi
        elif [[ "$result" == "true" ]]; then
          echo "✅ Assignment verification succeeded: \"$COMMITTER_EMAIL\" has $REQUIREMENT_NAME"
          echo "requirement_name=$REQUIREMENT_NAME" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "❌ Assignment verification failed: \"$COMMITTER_EMAIL\" has non-completed $REQUIREMENT_ΝΟΤΜΕΤ_NAME"
          echo "requirement_name=$REQUIREMENT_NAME" >> $GITHUB_OUTPUT
          exit 1
        fi

    # 3) Comment on PR if verification fails
    - name: Add comment via GH CLI
      if: failure() && steps.verify_assignments.conclusion == 'failure'
      shell: bash
      env:
        COMMITTER_EMAIL: ${{ steps.extract.outputs.committer_email }}
        REQUIREMENT_NAME: ${{ steps.verify_assignments.outputs.requirement_name }}
        PR_NO: ${{ steps.extract.outputs.pr_no }}
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        # Add comment to the Pull Request
        # Create a temporary file for the comment body
        TEMP_FILE=$(mktemp)

        # Start building the Markdown content
        {
          echo '### ❌ Merge Request Blocked'
          echo
          echo "**User**: ${COMMITTER_EMAIL}"
          echo
          echo "To proceed, you must have **${REQUIREMENT_NAME}**."
          echo
          echo "Please visit [SecureFlag](https://www.secureflag.com/) to view and complete your assignments."
        } > "$TEMP_FILE"

        # Post the comment using the file content
        gh issue comment "$PR_NO" --body-file "$TEMP_FILE"

        # Clean up
        rm "$TEMP_FILE"
