name: 'Vulnerability Training Check'
description: 'Blocks push if employee is not trained on specific vulnerability'
inputs:
  target_repo:
    description: 'Repository to check advisories in (format: owner/repo)'
    required: true
    default: ${{ github.repository }}
  sec_token:
    description: 'GitHub PAT with security advisory read access'
    required: true
  api_endpoint:
    description: 'SecureFlag API endpoint'
    required: true
  api_token:
    description: 'SecureFlag API token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 1) Extract GHSA ID and committer email
    - name: Find security reference
      id: extract
      shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" = "push" ]; then
          range="${{ github.event.before }}..${{ github.event.after }}"
          COMMITTER_EMAIL=$(git log -1 --pretty=format:"%ce" ${{ github.event.after }})
        else
          range="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
          COMMITTER_EMAIL=$(git log --pretty=format:"%ae" -n 1 ${{ github.event.pull_request.head.sha }})
        fi

        COMMIT_MESSAGES=$(git log --pretty=format:"%s" $range)
        GHSA_ID=$(echo "$COMMIT_MESSAGES" | grep -oE 'GHSA-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}' | head -n 1)

        echo "ghsa_id=$GHSA_ID" >> $GITHUB_OUTPUT
        echo "commiter_email=$COMMITTER_EMAIL" >> $GITHUB_OUTPUT
        echo "Extracted GHSA ID: $GHSA_ID"

    # 2) Check target repo's advisories
    - name: Verify advisory
      id: check_sec_adv
      if: steps.extract.outputs.ghsa_id != ''
      shell: bash
      env:
        GHSA_ID: ${{ steps.extract.outputs.ghsa_id }}
      run: |
        RESPONSE=$(curl -s \
          -H "Authorization: Bearer ${{ inputs.sec_token }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ inputs.target_repo }}/security-advisories/${GHSA_ID}")

        advisory_summary=$(echo "$RESPONSE" | jq -r '.summary // empty')
        if [ -z "$advisory_summary" ]; then
          echo "::error::Advisory $GHSA_ID not found in ${{ inputs.target_repo }}"
        else
          echo "Advisory Summary: $advisory_summary"
        fi
        echo "advisory_summary=$advisory_summary" >> $GITHUB_OUTPUT

    # 3) Call SecureFlag API
    - name: Verify training
      id: verify_training
      if: steps.extract.outputs.ghsa_id != '' && steps.check_sec_adv.outputs.advisory_summary != ''
      shell: bash
      env:
        SUMMARY: ${{ steps.check_sec_adv.outputs.advisory_summary }}
        COMMITTER_EMAIL: ${{ steps.extract.outputs.commiter_email }}
        GHSA_ID: ${{ steps.extract.outputs.ghsa_id }}

      run: |
        response=$(curl -s \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -H "Content-Type: application/json" \
          -d "{\"issueTitle\":\"$SUMMARY\",\"user\":\"$COMMITTER_EMAIL\",\"days\":\"365\"}" \
          ${{ inputs.api_endpoint }})

        result=$(echo "$response" | jq -r '.result')
        error=$(echo "$response" | jq -r '.error')
        vulnerability=$(echo "$response" | jq -r '.vulnerability')

        if [ "$result" = true ] || [ "$error" = true ];then
          echo "Training verification succeeded: User $COMMITTER_EMAIL completed training on the topics found in $GHSA_ID (\"$SUMMARY\"), action is approved"
        else
          echo "::error:: Training verification failed: User $COMMITTER_EMAIL has not completed required training for $GHSA_ID (\"$SUMMARY\"), action is refused"
          echo "vulnerability=$vulnerability" >> $GITHUB_OUTPUT
          exit 1
        fi

    # 4) Comment on PR if training fails
    - name: Add training required comment
      if: failure() && steps.verify_training.conclusion == 'failure' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ inputs.sec_token }}
        COMMITTER_EMAIL: ${{ steps.extract.outputs.commiter_email }}
        VULNERABILITY: ${{ steps.verify_training.outputs.vulnerability }}
      with:
        script: |
          try {
            const encodedVulnerability = encodeURIComponent(process.env.VULNERABILITY);
            const trainingUrl = `https://www.secureflag.com/go.html?type=search&c=${encodedVulnerability}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### ❌ Merge request blocked\n\n**User**: ${process.env.COMMITTER_EMAIL}\nMust complete at least one training lab in the security category "${process.env.VULNERABILITY}" to proceed.\nClick *[here](${trainingUrl})* to play a lab.`
            });
          } catch (error) {
            core.error(`Failed to create comment: ${error}`);
          }