name: SecureFlag Repo To Threat Model
description: Analyze your codebase and generate threat models using SecureFlag's ThreatCanvas.
branding:
  icon: shield
  color: blue

inputs:
  SECUREFLAG_API_KEY:
    description: SecureFlag API key
    required: true
  ANTHROPIC_API_KEY:
    description: Anthropic API key for AI features
    required: true
  SECUREFLAG_MODEL_UUID:
    description: SecureFlag model UUID
    required: true
  SECUREFLAG_COMMANDS:
    description: Commands to run
    required: false
    default: model-repo
  SECUREFLAG_REPO_PATH:
    description: Restrict analysis to a specific directory
    required: false
  SECUREFLAG_COMPONENT_LIMIT:
    description: Hinted number of nodes in TC diagrams
    required: false

runs:
  using: docker
  image: docker://registry.gitlab.com/secureflag-community/sf-runner:latest
  entrypoint: /app/entrypoint.sh
  env:
    SECUREFLAG_API_KEY: ${{ inputs.SECUREFLAG_API_KEY }}
    ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
    SECUREFLAG_MODEL_UUID: ${{ inputs.SECUREFLAG_MODEL_UUID }}
    SECUREFLAG_COMMANDS: ${{ inputs.SECUREFLAG_COMMANDS }}
    SECUREFLAG_REPO_PATH: ${{ inputs.SECUREFLAG_REPO_PATH }}
    SECUREFLAG_COMPONENT_LIMIT: ${{ inputs.SECUREFLAG_COMPONENT_LIMIT }}
