name: SecureFlag Repo To Threat Model
description: Analyze your codebase and generate threat models using SecureFlag's ThreatCanvas.
branding:
  icon: shield
  color: blue

inputs:
  api_key:
    description: SecureFlag API key
    required: true
  anthropic_key:
    description: Anthropic API key for AI features
    required: true
  model_uuid:
    description: SecureFlag model UUID
    required: true
  commands:
    description: Commands to run
    required: false
    default: model-repo
  repo_path:
    description: Restrict analysis to a specific directory
    required: false
  component_limit:
    description: Hinted number of nodes in TC diagrams
    required: false

runs:
  using: composite
  steps:
    - name: Run SecureFlag CI Runner
      shell: bash
      env:
        SECUREFLAG_API_KEY: ${{ inputs.api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_key }}
        SECUREFLAG_MODEL_UUID: ${{ inputs.model_uuid }}
        SECUREFLAG_COMMANDS: ${{ inputs.commands }}
        SECUREFLAG_REPO_PATH: ${{ inputs.repo_path }}
        SECUREFLAG_COMPONENT_LIMIT: ${{ inputs.component_limit }}
      run: |
        docker run --rm \
          -e SECUREFLAG_API_KEY \
          -e ANTHROPIC_API_KEY \
          -e SECUREFLAG_MODEL_UUID \
          -e SECUREFLAG_COMMANDS \
          ${SECUREFLAG_REPO_PATH:+-e SECUREFLAG_REPO_PATH} \
          ${SECUREFLAG_COMPONENT_LIMIT:+-e SECUREFLAG_COMPONENT_LIMIT} \
          -v "${{ github.workspace }}:/repo" \
          -w /repo \
          registry.gitlab.com/secureflag-community/sf-runner:latest \
          /app/entrypoint.sh
