name: SecureFlag Repo To Threat Model
description: Analyze your codebase and generate threat models using SecureFlag's ThreatCanvas.
branding:
  icon: shield
  color: blue

inputs:
  SECUREFLAG_API_KEY:
    description: SecureFlag API key
    required: true
  SECUREFLAG_MODEL_UUID:
    description: SecureFlag model UUID
    required: true
  SECUREFLAG_COMMANDS:
    description: Commands to run
    required: false
    default: model-repo
  SECUREFLAG_REPO_PATH:
    description: Restrict analysis to a specific directory
    required: false
  SECUREFLAG_COMPONENT_LIMIT:
    description: Hinted number of nodes in TC diagrams
    required: false
  # AI Provider - Option 1: Anthropic
  ANTHROPIC_API_KEY:
    description: Anthropic API key for AI features
    required: false
  ANTHROPIC_MODEL:
    description: 'Anthropic model name (default: claude-sonnet-4-20250514)'
    required: false
  # AI Provider - Option 2: OpenAI
  OPENAI_API_KEY:
    description: OpenAI API key for AI features
    required: false
  OPENAI_MODEL:
    description: 'OpenAI model name (default: gpt-4o)'
    required: false
  # AI Provider - Option 3: Azure OpenAI
  AZURE_OPENAI_KEY:
    description: Azure OpenAI API key
    required: false
  AZURE_OPENAI_ENDPOINT:
    description: 'Azure OpenAI endpoint URL (e.g., https://your-resource.openai.azure.com/)'
    required: false
  AZURE_OPENAI_DEPLOYMENT:
    description: Azure OpenAI deployment name
    required: false
  AZURE_OPENAI_API_VERSION:
    description: 'Azure OpenAI API version (default: 2024-02-15-preview)'
    required: false

runs:
  using: docker
  image: docker://registry.gitlab.com/secureflag-community/sf-runner:latest
  entrypoint: /app/entrypoint.sh
  env:
    SECUREFLAG_API_KEY: ${{ inputs.SECUREFLAG_API_KEY }}
    SECUREFLAG_MODEL_UUID: ${{ inputs.SECUREFLAG_MODEL_UUID }}
    SECUREFLAG_COMMANDS: ${{ inputs.SECUREFLAG_COMMANDS }}
    SECUREFLAG_REPO_PATH: ${{ inputs.SECUREFLAG_REPO_PATH }}
    SECUREFLAG_COMPONENT_LIMIT: ${{ inputs.SECUREFLAG_COMPONENT_LIMIT }}
    # AI Provider variables (configure one)
    ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
    ANTHROPIC_MODEL: ${{ inputs.ANTHROPIC_MODEL }}
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    OPENAI_MODEL: ${{ inputs.OPENAI_MODEL }}
    AZURE_OPENAI_KEY: ${{ inputs.AZURE_OPENAI_KEY }}
    AZURE_OPENAI_ENDPOINT: ${{ inputs.AZURE_OPENAI_ENDPOINT }}
    AZURE_OPENAI_DEPLOYMENT: ${{ inputs.AZURE_OPENAI_DEPLOYMENT }}
    AZURE_OPENAI_API_VERSION: ${{ inputs.AZURE_OPENAI_API_VERSION }}
